### ISSUE TITLE
Transferring import statements to __init__

### ISSUE THREAD

**Issue by CaptainCodeAU** [arbusam/Video-Downloader#3]
https://github.com/arbusam/Video-Downloader/blob/e7230a60db0315b0c8cc84bed8ffd69b25cf4a11/url_dump/main.py#L1

Feel free to move all import statements into __init__.py

Reasons -
1. cleaner and more structured code
2. prevent potential duplicate calls in the future

**Comment by arbusam** [comment]
This was fixed in the master branch.
