### ISSUE TITLE
Reusable 'download type' list

### ISSUE THREAD

**Issue by CaptainCodeAU** [arbusam/Video-Downloader#7]
https://github.com/arbusam/Video-Downloader/blob/9ed57aa48c55e816c283f6bf479e20359b3f705d/url_dump/url_dump.py#L16

https://github.com/arbusam/Video-Downloader/blob/9ed57aa48c55e816c283f6bf479e20359b3f705d/url_dump/url_dump.py#L89-L112

What if you move the download type and the respective descriptions into a dictionary?

This way you can avoid hardcoding the download types multiple times in your code.

**Comment by arbusam** [comment]
Fixed in the master branch
