### ISSUE TITLE
Colour formatting in messages

### ISSUE THREAD

**Issue by CaptainCodeAU** [arbusam/Video-Downloader#8]
https://github.com/arbusam/Video-Downloader/blob/9ed57aa48c55e816c283f6bf479e20359b3f705d/url_dump/includes/errors.py#L5

Good use of colours in error messages.

One small thing...
"Fore.WHITE" is outside the string. But the rest of it is formatted f"".
Avoid mixing the two styles. Use either one.

**Comment by arbusam** [comment]
Fixed in the master branch
