### ISSUE TITLE
Common configuration

### ISSUE THREAD

**Issue by CaptainCodeAU** [arbusam/Video-Downloader#9]
https://github.com/arbusam/Video-Downloader/blob/9ed57aa48c55e816c283f6bf479e20359b3f705d/db/config.py#L1

Is this the common configuration file?

The code structure, elegance and readability is as important as the problem it is trying to solve. :)
I don't doubt your ability to solve a coding challenge. In Intermediate Python, I would like you (and everyone) to give equal emphasis on the code structure too. Feel free to come up with more elegant solutions.

**Comment by arbusam** [comment]
This is the common configuration file for the db. That's why it is in the db folder.

**Comment by CaptainCodeAU** [comment]
Then where is your common folder?

**Comment by arbusam** [comment]
Fixed in the master branch
